courses/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


from . import views

app_name = 'courses'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^add/$', views.CourseCreate.as_view(), name='add'),
	url(r'^(?P<pk>[0-9]+)/change/$', views.CourseEdit.as_view(), name='edit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^courses/', include('courses.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from django.urls import reverse


from PIL import Image

DURATION_CHOICES = [
	(2, '2 Weeks'),
	(8, '8 Weeks'),
]

class Course(models.Model):
	title = models.CharField(max_length = 50, default ="Name it something good")
	description = models.TextField()
	instructor = models.CharField(max_length = 50, default = "Django Guru")
	duration = models.IntegerField(choices=DURATION_CHOICES, default = 8)
	art = models.ImageField(upload_to='courseart/')

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:detail', kwargs={'pk': self.pk})

courses/forms.py
from django import forms
from django.forms.widgets import RadioSelect
from django.db import models
#from models import Post
from courses.models import Course			

class CourseForm(forms.ModelForm):
	class Meta:
		model = Course
		fields = ['title', 'description','instructor','duration', 'art',]
		
		widgets = {
			'duration': RadioSelect(),
			#'description': StyledTextBox(),
			'art': forms.FileInput()
		}				
		
		labels = {
			'title': ('Course Title'),
			'duration': ('Course Duration'),
		}

		help_texts = { 'description': ('</br><div id="helptext">Provide some information about what students will learn.</div>')}
	
		methods = {
			'art' : ('post'),
		}

		enctypes = {
			'art': ('multipart/form-data'),
		}

		

courses/views.py
from django.http import HttpResponseRedirect 
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from courses.models import Course
from courses.forms import CourseForm


class IndexView(generic.ListView):
	template_name = 'courses/index.html'
	model = Course

class DetailView(generic.DetailView):
	model = Course
	template_name = 'courses/detail.html'

class CourseCreate(CreateView):
	form_class = CourseForm
	template_name = 'courses/add.html'
	success_url = reverse_lazy('courses:index')
	
	def get_success_url(self):
		return reverse_lazy('courses:index')

class CourseEdit(UpdateView):
	form_class = CourseForm
	model = Course
	template_name = 'courses/add.html'

courses/templates/courses/add.html
{%load static%}

<link rel="stylesheet" type="text/css" href="{%static 'courses/style.css' %}" />
<div id="nav">
	<ul>
		<li>Programming Django</li>
		<li><a href="{% url 'courses:index' %}">Course Catalog</a></li>
		<li><a href="{% url 'courses:add' %}">Add Course</a></li>
	</ul>
</div>

<h1>Add Course</h1>

<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
	<ul id="form">
		{{form.as_ul}}
	</ul>

<div class="right">
	<input type="submit" value="Save"> or <a href="{% url 'courses:index' %}">Cancel</a>
</div>

</form>

courses/templates/courses/detail.html
{%load static%}

<link rel="stylesheet" type="text/css" href="{%static 'courses/style.css' %}" />
<div id="nav">
	<ul>
		<li>Programming Django</li>
		<li><a href="{% url 'courses:index' %}">Course Catalog</a></li>
		<li><a href="{% url 'courses:add' %}">Add Course</a></li>
	</ul>
</div>

<h1>{{course.title}}</h1>
<form action="/courses/{{course.id}}/change" id="change" >
	<input type="submit" value="Change"/>
</form>

<h3>{{course.description}}</h3>

<img src="{{MEDIA_URL}}/{{course.art.url}}" width="300"/>
<ul id="details">
	<li>Instructor: {{course.instructor}}</li>
	<li>Duration: {{course.duration}} Weeks</p></li>
</ul>

courses/templates/courses/index.html
{%load static%}

<link rel="stylesheet" type="text/css" href="{%static 'courses/style.css' %}" />
<div id="nav">
	<ul>
		<li>Programming Django</li>
		<li><a href="{% url 'courses:index' %}">Course Catalog</a></li>
		<li><a href="{% url 'courses:add' %}">Add Course</a></li>
	</ul>
</div>

{% if course_list %}
	<h1>Django Course Catalog</h1>
	<p>Please select from our awesome courses!</p>
	<table id="c_list">
	   <tr>
		<th>#</th>
		<th>Course Title</th>
		<th>Instructor</th>
		<th>Duration</th>
		<th></th>
	   </tr>
	{% for course in course_list %}
	   <tr>	
		<td>{{course.id}}</td>
		<td><a href="{% url 'courses:detail' course.id%}">{{course.title}}</a></td>
		<td>{{course.instructor}}</td>
		<td>{{course.duration}} weeks</td>
		<td><a href="{% url 'courses:edit' course.id%}">Edit</a></td>
	   </tr>
	{%endfor%}
	</table>

{% else %}
	<p>No courses are available.</p>
{% endif %}